basePath: /location/v3/
definitions:
  responses.ZoneResponse:
    properties:
      numberOfAccessPoints:
        description: The number of access points within the zone
        type: integer
      numberOfUnserviceableAccessPoints:
        description: Number of inoperable access points within the zone.
        type: integer
      numberOfUsers:
        description: The number of users currently on the access point.
        type: integer
      resourceURL:
        description: Self referring URL
        type: string
      zoneId:
        description: Identifier of zone
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: Iulisloi Zacarias
    url: https://github.com/izacarias
  description: The ETSI MEC ISG MEC013 Location API described using OpenAPI
  license:
    name: BSD-3-Clause
    url: https://forge.etsi.org/legal-matters
  title: ETSI GS MEC 013 - Location API
  version: 3.1.1
paths:
  /queries/zones:
    get:
      description: The GET method is used to query the information about one or more
        specific zones or a list of zones.
      operationId: zonesGET
      parameters:
      - collectionFormat: csv
        description: Zone ID
        in: query
        items:
          type: string
        name: zoneId
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.ZoneResponse'
            type: array
        "500":
          description: Internal Server Error
      summary: Query the information about one or more specific zones or a list of
        zones.
      tags:
      - location
  /queries/zones/{zoneId}:
    get:
      responses:
        "500":
          description: Internal Server Error
schemes:
- http
swagger: "2.0"
